// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEGl53jG389lRfeJMnZY9uojj3KkG61Us',
    appId: '1:809876907397:web:9f32ff67f9ee8a27a550ec',
    messagingSenderId: '809876907397',
    projectId: 'mal3ab-33199',
    authDomain: 'mal3ab-33199.firebaseapp.com',
    storageBucket: 'mal3ab-33199.firebasestorage.app',
    measurementId: 'G-V61RWNRR1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ5Vx0sjYBZt0Yg8YzL1qLc3dX5aTud48',
    appId: '1:809876907397:android:4f8883efb94a83dca550ec',
    messagingSenderId: '809876907397',
    projectId: 'mal3ab-33199',
    storageBucket: 'mal3ab-33199.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0p8_9yU5_Do_KoMhW6IKqn6T7xHpOcQ',
    appId: '1:809876907397:ios:3bca548d6d690f93a550ec',
    messagingSenderId: '809876907397',
    projectId: 'mal3ab-33199',
    storageBucket: 'mal3ab-33199.firebasestorage.app',
    iosBundleId: 'com.example.mal3ab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0p8_9yU5_Do_KoMhW6IKqn6T7xHpOcQ',
    appId: '1:809876907397:ios:3bca548d6d690f93a550ec',
    messagingSenderId: '809876907397',
    projectId: 'mal3ab-33199',
    storageBucket: 'mal3ab-33199.firebasestorage.app',
    iosBundleId: 'com.example.mal3ab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEGl53jG389lRfeJMnZY9uojj3KkG61Us',
    appId: '1:809876907397:web:6cc212aabb77e020a550ec',
    messagingSenderId: '809876907397',
    projectId: 'mal3ab-33199',
    authDomain: 'mal3ab-33199.firebaseapp.com',
    storageBucket: 'mal3ab-33199.firebasestorage.app',
    measurementId: 'G-HDKR99YSCY',
  );
}
